[CmdletBinding()]
param(
    [string]$Htdocs = '',
    [string]$BaseUrl = 'http://localhost',
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
if ($Htdocs -eq '') {
    $Htdocs = Split-Path $ProjectRoot -Parent
}
$Htdocs = (Resolve-Path $Htdocs).Path
$ProjectParent = Split-Path $ProjectRoot -Parent
$ProjectFolder = Split-Path $ProjectRoot -Leaf

if ($ProjectRoot -eq $Htdocs) {
    Write-Host 'The project is already the htdocs root. Root index.php and .htaccess are ready.' -ForegroundColor Green
} else {
    if ($ProjectParent -ne $Htdocs) {
        throw 'The project must be a direct child of the selected htdocs directory.'
    }
    if ($ProjectFolder -notmatch '^[A-Za-z0-9._-]+$') {
        throw 'Rename the project folder to use only letters, numbers, dot, underscore or hyphen before installing the root launcher.'
    }

    $rootIndex = Join-Path $Htdocs 'index.php'
    $rootHtaccess = Join-Path $Htdocs '.htaccess'
    $marker = 'NCP_ROOT_LAUNCHER'
    $indexOwned = (Test-Path $rootIndex) -and ((Get-Content $rootIndex -Raw) -match $marker)
    $htaccessOwned = (Test-Path $rootHtaccess) -and ((Get-Content $rootHtaccess -Raw) -match $marker)
    $foreignLauncherFile = ((Test-Path $rootIndex) -and -not $indexOwned) -or ((Test-Path $rootHtaccess) -and -not $htaccessOwned)

    if ($foreignLauncherFile -and -not $Force) {
        throw "htdocs already has an index.php or .htaccess (normally the XAMPP dashboard). Re-run with -Force to back them up and install the college site at localhost/."
    }

    if ($Force -and ((Test-Path $rootIndex) -or (Test-Path $rootHtaccess))) {
        $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
        $backup = Join-Path $ProjectRoot "storage\backups\root-launcher-$stamp"
        New-Item -ItemType Directory -Path $backup -Force | Out-Null
        if (Test-Path $rootIndex) { Copy-Item $rootIndex (Join-Path $backup 'index.php') -Force }
        if (Test-Path $rootHtaccess) { Copy-Item $rootHtaccess (Join-Path $backup '.htaccess') -Force }
        Write-Host "Existing htdocs launcher files were backed up to $backup" -ForegroundColor Yellow
    }

    $indexContent = @"
<?php
/* NCP_ROOT_LAUNCHER - generated by scripts/install-xampp-root.ps1 */
declare(strict_types=1);
require __DIR__ . '/$ProjectFolder/public/index.php';
"@

    $htaccessContent = @"
# NCP_ROOT_LAUNCHER - generated by scripts/install-xampp-root.ps1
Options -Indexes
DirectoryIndex index.php
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^\. - [F,L]
    RewriteCond %{THE_REQUEST} \s/+${ProjectFolder}(?:[/?\s]) [NC]
    RewriteRule ^${ProjectFolder}(?:/|$) - [F,L]
    RewriteRule ^assets(?:/(.*))?$ ${ProjectFolder}/public/assets/`$1 [L,NC]
    RewriteRule ^install/?$ ${ProjectFolder}/public/install/index.php [QSA,L,NC,E=NCP_ROOT_LAUNCHER:1]
    RewriteRule ^install/(.*)$ ${ProjectFolder}/public/install/`$1 [L,NC,E=NCP_ROOT_LAUNCHER:1]
    RewriteRule ^(preview\.html|student-preview\.html|admin-preview\.html)$ ${ProjectFolder}/public/`$1 [L,NC]
    RewriteRule ^$ index.php [QSA,L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.php [QSA,L]
</IfModule>
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
</IfModule>
<FilesMatch "^\.">
    Require all denied
</FilesMatch>
"@

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($rootIndex, $indexContent, $utf8NoBom)
    [System.IO.File]::WriteAllText($rootHtaccess, $htaccessContent, $utf8NoBom)
    Write-Host "Installed the localhost root launcher for project folder '$ProjectFolder'." -ForegroundColor Green
}

$envPath = Join-Path $ProjectRoot '.env'
if (Test-Path $envPath) {
    $envText = Get-Content $envPath -Raw
    if ($envText -match '(?m)^APP_URL=') {
        $envText = [regex]::Replace($envText, '(?m)^APP_URL=.*$', "APP_URL=$($BaseUrl.TrimEnd('/'))")
    } else {
        $envText = "APP_URL=$($BaseUrl.TrimEnd('/'))`r`n" + $envText
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($envPath, $envText, $utf8NoBom)
    Write-Host "Updated APP_URL to $($BaseUrl.TrimEnd('/'))." -ForegroundColor Green
} else {
    Write-Host 'No .env exists yet. The browser installer will save the root URL.' -ForegroundColor Yellow
}

Write-Host 'Restart Apache, then open the BaseUrl shown above. Do not add the project folder or /public.' -ForegroundColor Cyan
